# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_code', models.CharField(max_length=30, unique=True, verbose_name='Candidate Code')),
                ('candidate', models.CharField(max_length=30, verbose_name='Candidate Name')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Question')),
            ],
        ),
    ]
